//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.5.1
//     from Assets/Player Inputs.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputs: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputs()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Player Inputs"",
    ""maps"": [
        {
            ""name"": ""Swipe Actions"",
            ""id"": ""440a2059-cc6e-4bfd-a296-719226ff097a"",
            ""actions"": [
                {
                    ""name"": ""PrimaryContact"",
                    ""type"": ""PassThrough"",
                    ""id"": ""d6d2e103-d8a8-4444-a4b9-6d8cbca5a029"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PrimaryPosition"",
                    ""type"": ""PassThrough"",
                    ""id"": ""9a203782-375e-4344-89a1-5f23359ec7f4"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""ad20d1c5-5b1a-4ac7-97a7-4a8ece09926b"",
                    ""path"": ""<Touchscreen>/primaryTouch/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrimaryContact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""50b400e0-f210-49e2-b337-356892333863"",
                    ""path"": ""<Touchscreen>/primaryTouch/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrimaryPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Ball Behaviour Actions"",
            ""id"": ""19f4c564-0c17-4a5c-9666-8b43ebba09ee"",
            ""actions"": [
                {
                    ""name"": ""BallAxisX"",
                    ""type"": ""Value"",
                    ""id"": ""06265ed5-c638-4ea6-8398-579b78f54723"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""BallAxisY"",
                    ""type"": ""Value"",
                    ""id"": ""b1a2b827-e16d-470a-95bb-3297c3c0e2f7"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""ae6db471-4b3d-4b3b-a37f-e6a25b59cab9"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BallAxisX"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""dcd7cad0-1541-42bf-aacd-468d43f3ee03"",
                    ""path"": ""<Touchscreen>/primaryTouch/delta/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BallAxisX"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""cec46581-9812-47b9-8fa2-1a9751147912"",
                    ""path"": ""<Touchscreen>/primaryTouch/delta/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BallAxisX"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""b30f461f-4ed1-4e78-b4f3-5f788fb28e77"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BallAxisY"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""c02e9b32-0589-4400-a09f-ff7e72c2298d"",
                    ""path"": ""<Touchscreen>/primaryTouch/delta/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BallAxisY"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""b0b0089d-464f-4370-be35-ffc124d40f6e"",
                    ""path"": ""<Touchscreen>/primaryTouch/delta/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BallAxisY"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Swipe Actions
        m_SwipeActions = asset.FindActionMap("Swipe Actions", throwIfNotFound: true);
        m_SwipeActions_PrimaryContact = m_SwipeActions.FindAction("PrimaryContact", throwIfNotFound: true);
        m_SwipeActions_PrimaryPosition = m_SwipeActions.FindAction("PrimaryPosition", throwIfNotFound: true);
        // Ball Behaviour Actions
        m_BallBehaviourActions = asset.FindActionMap("Ball Behaviour Actions", throwIfNotFound: true);
        m_BallBehaviourActions_BallAxisX = m_BallBehaviourActions.FindAction("BallAxisX", throwIfNotFound: true);
        m_BallBehaviourActions_BallAxisY = m_BallBehaviourActions.FindAction("BallAxisY", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Swipe Actions
    private readonly InputActionMap m_SwipeActions;
    private List<ISwipeActionsActions> m_SwipeActionsActionsCallbackInterfaces = new List<ISwipeActionsActions>();
    private readonly InputAction m_SwipeActions_PrimaryContact;
    private readonly InputAction m_SwipeActions_PrimaryPosition;
    public struct SwipeActionsActions
    {
        private @PlayerInputs m_Wrapper;
        public SwipeActionsActions(@PlayerInputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @PrimaryContact => m_Wrapper.m_SwipeActions_PrimaryContact;
        public InputAction @PrimaryPosition => m_Wrapper.m_SwipeActions_PrimaryPosition;
        public InputActionMap Get() { return m_Wrapper.m_SwipeActions; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(SwipeActionsActions set) { return set.Get(); }
        public void AddCallbacks(ISwipeActionsActions instance)
        {
            if (instance == null || m_Wrapper.m_SwipeActionsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_SwipeActionsActionsCallbackInterfaces.Add(instance);
            @PrimaryContact.started += instance.OnPrimaryContact;
            @PrimaryContact.performed += instance.OnPrimaryContact;
            @PrimaryContact.canceled += instance.OnPrimaryContact;
            @PrimaryPosition.started += instance.OnPrimaryPosition;
            @PrimaryPosition.performed += instance.OnPrimaryPosition;
            @PrimaryPosition.canceled += instance.OnPrimaryPosition;
        }

        private void UnregisterCallbacks(ISwipeActionsActions instance)
        {
            @PrimaryContact.started -= instance.OnPrimaryContact;
            @PrimaryContact.performed -= instance.OnPrimaryContact;
            @PrimaryContact.canceled -= instance.OnPrimaryContact;
            @PrimaryPosition.started -= instance.OnPrimaryPosition;
            @PrimaryPosition.performed -= instance.OnPrimaryPosition;
            @PrimaryPosition.canceled -= instance.OnPrimaryPosition;
        }

        public void RemoveCallbacks(ISwipeActionsActions instance)
        {
            if (m_Wrapper.m_SwipeActionsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ISwipeActionsActions instance)
        {
            foreach (var item in m_Wrapper.m_SwipeActionsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_SwipeActionsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public SwipeActionsActions @SwipeActions => new SwipeActionsActions(this);

    // Ball Behaviour Actions
    private readonly InputActionMap m_BallBehaviourActions;
    private List<IBallBehaviourActionsActions> m_BallBehaviourActionsActionsCallbackInterfaces = new List<IBallBehaviourActionsActions>();
    private readonly InputAction m_BallBehaviourActions_BallAxisX;
    private readonly InputAction m_BallBehaviourActions_BallAxisY;
    public struct BallBehaviourActionsActions
    {
        private @PlayerInputs m_Wrapper;
        public BallBehaviourActionsActions(@PlayerInputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @BallAxisX => m_Wrapper.m_BallBehaviourActions_BallAxisX;
        public InputAction @BallAxisY => m_Wrapper.m_BallBehaviourActions_BallAxisY;
        public InputActionMap Get() { return m_Wrapper.m_BallBehaviourActions; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(BallBehaviourActionsActions set) { return set.Get(); }
        public void AddCallbacks(IBallBehaviourActionsActions instance)
        {
            if (instance == null || m_Wrapper.m_BallBehaviourActionsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_BallBehaviourActionsActionsCallbackInterfaces.Add(instance);
            @BallAxisX.started += instance.OnBallAxisX;
            @BallAxisX.performed += instance.OnBallAxisX;
            @BallAxisX.canceled += instance.OnBallAxisX;
            @BallAxisY.started += instance.OnBallAxisY;
            @BallAxisY.performed += instance.OnBallAxisY;
            @BallAxisY.canceled += instance.OnBallAxisY;
        }

        private void UnregisterCallbacks(IBallBehaviourActionsActions instance)
        {
            @BallAxisX.started -= instance.OnBallAxisX;
            @BallAxisX.performed -= instance.OnBallAxisX;
            @BallAxisX.canceled -= instance.OnBallAxisX;
            @BallAxisY.started -= instance.OnBallAxisY;
            @BallAxisY.performed -= instance.OnBallAxisY;
            @BallAxisY.canceled -= instance.OnBallAxisY;
        }

        public void RemoveCallbacks(IBallBehaviourActionsActions instance)
        {
            if (m_Wrapper.m_BallBehaviourActionsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IBallBehaviourActionsActions instance)
        {
            foreach (var item in m_Wrapper.m_BallBehaviourActionsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_BallBehaviourActionsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public BallBehaviourActionsActions @BallBehaviourActions => new BallBehaviourActionsActions(this);
    public interface ISwipeActionsActions
    {
        void OnPrimaryContact(InputAction.CallbackContext context);
        void OnPrimaryPosition(InputAction.CallbackContext context);
    }
    public interface IBallBehaviourActionsActions
    {
        void OnBallAxisX(InputAction.CallbackContext context);
        void OnBallAxisY(InputAction.CallbackContext context);
    }
}
